---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#registering-variables-with-a-loop
- name: Check versions
  shell: /usr/local/bin/{{ item.name }} {{ item.version_flag }}
  loop: "{{ binary_tools }}"
  loop_control:
    label: "{{ item.name }}-{{ item.version }}"
  register: checked_version
  failed_when: checked_version.rc not in [0, 127]
  changed_when: no
  check_mode: no
  vars:
    binary_tools:
    - name: kubectl
      version: "{{ kubectl_version }}"
      url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
      version_flag: version --client --short
      unarchive: no
    - name: kind
      version: "{{ kind_version }}"
      url: https://github.com/kubernetes-sigs/kind/releases/download/v{{ kind_version }}/kind-linux-amd64
      version_flag: version
      unarchive: no
    - name: helm
      version: "{{ helm_version }}"
      url: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
      version_flag: version --short
      unarchive: yes
      extra_opts:
        - --strip-components=1
        - linux-amd64/helm


- name: Download tools
  get_url:
    url: "{{ result.item.url }}"
    dest: /usr/local/bin/{{ result.item.name }}
    mode: 755
    force: yes
  loop: "{{ checked_version.results }}"
  loop_control:
    loop_var: result
    label: "{{ result.item.name }}-{{ result.item.version }}"
  when: (result.item.version not in result.stdout) and not (result.item.unarchive | bool)
  become: yes


- name: Download and unarchive tools
  unarchive:
    src: "{{ result.item.url }}"
    dest: /usr/local/bin
    mode: 755
    remote_src: yes
    extra_opts: "{{ result.item.extra_opts }}"
  loop: "{{ checked_version.results }}"
  loop_control:
    loop_var: result
    label: "{{ result.item.name }}-{{ result.item.version }}"
  when: (result.item.version not in result.stdout) and (result.item.unarchive | bool)
  become: yes


# FIXME: Install ghq
# unzip で特定ファイルのみ、ディレクトリを除いて解凍する方法がないため仕方なく
# あとなぜか実行ファイルのみ解凍できるのにエラーが出て落ちる

- name: Check ghq version
  shell: /usr/local/bin/ghq --version
  register: checked_ghq_version
  failed_when: checked_ghq_version.rc not in [0, 127]
  changed_when: no
  check_mode: no


- name: Download ghq
  unarchive:
    src: https://github.com/x-motemen/ghq/releases/download/v{{ ghq_version }}/ghq_linux_amd64.zip
    dest: /usr/local/bin
    mode: 755
    remote_src: yes
    extra_opts:
      - -j
    exclude:
      - '*/LICENSE'
      - '*/CHANGELOG.md'
      - '*/CREDITS'
      - '*/README.adoc'
      - '*/misc/*'
  when: ghq_version not in checked_ghq_version.stdout
  become: yes
