---
- name: Get zsh directory name
  shell: echo ${ZDOTDIR:-$HOME}
  register: zdotdir
  changed_when: no
  check_mode: no

- name: Install prezto repository
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ zdotdir.stdout }}/.zprezto"
    recursive: yes

- name: Find dotfiles
  find:
    paths: ~/dotfiles/files
    use_regex: yes
    patterns: "^[\\.].+$"
    recurse: no
    hidden: yes
    file_type: any
    excludes:
      - .git
      - .gitignore
      - .gitmodules
  register: found_dotfiles

- name: Make symbolic links
  # command: "ln -snfv {{ item }} {{ item | regex_replace('/dotfiles', '') }}"
  file:
    src: "{{ item }}"
    dest: "{{ item | regex_replace('/dotfiles/files', '') }}"
    state: link
    force: yes
  loop: "{{ found_dotfiles.files | map(attribute='path') | list }}"

- name: Change login shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  become: yes
