---
- name: Install anyenv repository
  git:
    repo: https://github.com/anyenv/anyenv
    dest: "{{ home }}/.anyenv"

- name: Initialize install manifest directory
  shell: "{{ home }}/.anyenv/bin/anyenv install --force-init"
  args:
    creates: "{{ home }}/.config/anyenv/anyenv-install"

- name: Install each env
  shell: "{{ home }}/.anyenv/bin/anyenv install {{ item }}"
  args:
    creates: "{{ home }}/.anyenv/envs/{{ item }}"
  with_items:
    - rbenv
    - nodenv

- name: Install ruby via rbenv
  import_tasks: rbenv.yml

- name: Install node via nodenv
  import_tasks: nodenv.yml
