---
- name: Install node {{ node_version }}
  shell: |
    nodenv install -s {{ node_version }}
    nodenv global {{ node_version }}
    nodenv rehash
  vars:
    nodenv_dir: "{{ home }}/.anyenv/envs/nodenv"
  args:
    creates: "{{ nodenv_dir }}/versions/{{ node_version }}"
  environment:
    PATH: "{{ nodenv_dir }}/bin:{{ nodenv_dir }}/plugins/node-build/bin:{{ ansible_env.PATH }}"
