---
- name: Install apt repository
  apt_repository:
    repo: ppa:linuxuprising/shutter # for shutter
  become: yes

- name: Install applications
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - gnome-tweaks
      - gnome-shell-extensions
      - terminator
      - shutter
  become: yes

- name: Install applications from snap
  snap:
    name: "{{ packages }}"
    classic: yes
  vars:
    packages:
      - code
      - android-studio
      - pycharm-community
      - slack
      - postman
  become: yes
