#!/bin/bash
set -eu

function has() {
  type "$1" &>/dev/null
}

BREW_PATH="$HOME/dotfiles/Brewfile"

echo ""
echo "===== Install homebrew ====="
echo ""

sleep 0.5
if has "brew"; then
    echo "Already installed."
elif has "git" && has "curl"; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else
  echo "Please install git and curl." 1>&2
  exit 1
fi
brew doctor

echo ""
echo "===== Execute 'brew install' ====="
echo ""

sleep 0.5
# virtualbox で躓くことがあるので先にインストールしておく
# if type virtualbox > /dev/null 2>&1; then
#     echo "Virtualbox is already installed."
# else
#     brew install --cask virtualbox
# fi
brew bundle --file="${BREW_PATH}"

echo ""
echo "Homebrew and packages are installed successfully."
echo ""
