#!/bin/bash
set -eu

function has() {
  type "$1" &>/dev/null
}

# asdf
echo ""
echo "===== Install asdf ====="
echo ""
sleep 0.5
if [[ -d "$HOME/.asdf" ]]; then
  echo "Already installed."
else
  git clone https://github.com/asdf-vm/asdf.git "$HOME/.asdf" --branch v0.10.0
fi

# shellcheck source=/dev/null
has "asdf" || source "$HOME/.asdf/asdf.sh"

echo ""
echo "===== Install asdf plugins ====="
echo ""
if has "asdf-plugin-install"; then
  asdf-plugin-install
else
  $HOME/dotfiles/bin/asdf-plugin-install
fi
asdf install

echo ""
echo "===== Setup asdf direnv ====="
echo ""
asdf direnv setup --shell zsh --version latest
