#!/bin/bash
set -eu

function has() {
  type "$1" &>/dev/null
}

# asdf
echo "===== Install asdf ====="
sleep 0.5
if [ -d "$HOME/.asdf" ]; then
  echo "Already installed."
  echo ""
else
  git clone https://github.com/asdf-vm/asdf.git "$HOME/.asdf" --branch v0.10.0
  # shellcheck source=/dev/null
  source "$HOME/.asdf/asdf.sh"
fi

if has "asdf" && has "asdf-install"; then
  asdf-install
else
  export PATH=$HOME/.asdf/bin:$HOME/dotfiles/bin:$PATH
  asdf-install
fi
