#!/bin/bash
set -eu

function has() {
  type "$1" &>/dev/null
}

# prezto
echo ""
echo "===== Install prezto ====="
echo ""
sleep 0.5
if [[ -d "${ZDOTDIR:-$HOME}/.zprezto" ]]; then
  echo "already installed"
else
  # prezto
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
  echo ""
  echo "Prezto is installed successfully."
  echo ""

fi

# powerline fonts
echo ""
echo "===== Install powerline fonts ====="
echo ""
sleep 0.5
if find ~/Library/Fonts -name "Ubuntu*" >/dev/null 2>&1; then
  echo "already installed"
else
  ~/dotfiles/fonts/install.sh
  echo ""
  echo "Powerline fonts are installed successfully."
  echo ""
fi

# setup fzf
echo ""
echo "===== Install fzf settings ====="
echo ""
if has "brew" && has "fzf" ; then
  "$(brew --prefix)"/opt/fzf/install \
    --key-bindings --no-completion --no-update-rc

  echo ""
  echo "FZF is configured successfully."
  echo ""
fi

echo "Set up your macOS successfully."
