---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
  become: yes

- name: Upgrade all apt packages
  apt:
    update_cache: yes
    upgrade: safe
  become: yes

- name: Add apt repository
  apt_repository:
    repo: "{{ item }}"
  loop:
    - ppa:git-core/ppa
  become: yes

- name: Install packages from apt
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - git
      - curl
      - vim
      - zsh
      - tmux
      - jq
      - python3-pip
      - tig
      - tree
      - htop
      - update-manager-core # 18.04 to 20.04
  become: yes

- name: Uninstall packages from apt
  apt:
    name:
      - golang-go # migrate to snap
    state: absent
    update_cache: yes
  become: yes

- name: Install packages from pip3
  pip:
    name:
      - awscli
    executable: pip3
    state: absent # uninstall
  become: yes

- name: Install packages from snap
  snap:
    name: "{{ packages }}"
    classic: yes
  vars:
    packages:
      - go
      - hub
      - starship
      - google-cloud-sdk
  become: yes
