---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
  become: true

- name: Upgrade all apt packages
  apt:
    update_cache: yes
    upgrade: safe
  become: true

- name: Add apt repository
  apt_repository:
    repo: ppa:longsleep/golang-backports
  become: yes

- name: Install packages from apt
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - git
      - curl
      - vim
      - zsh
      - tmux
      - jq
      - python3-pip
      - golang-go
  become: true

#- name: Upgrade pip3
#  command: pip3 install --upgrade pip
#  register: result
#  changed_when: '"Requirement already up-to-date" not in result.stdout'
#  become: true

- name: Install packages from pip3
  pip:
    name:
      - awscli
    executable: pip3
  become: true
